=== AhmedMohamedZein/ITI_XML/Day two/Untitled2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT company (employee+)>
<!ELEMENT employee (name,email,phones,addresses)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT addresses (address+)>
<!ELEMENT address (street,buildingnumber,region,city,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingnumber (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!-- <!ELEMENT city (#PCDATA)> -->
<!ELEMENT country (#PCDATA)>
<!ATTLIST employee id ID #REQUIRED >
<!ATTLIST phone type (home|work|mobile) #REQUIRED>


<!--– Info. of each employee consists of a name, phones,  addresses, and e-mail.
– The phones element may have more than phone element.
– Each phone element has one attribute called Type. The Type attribute takes one of the following values: home, work or mobile. 
– The addresses element may have more than address element.
– Each address element must consist of the following elements: Street,  Building Number, Region, City, and Country.
– The element e-mail must be exist for all employees.
-->

=== AhmedMohamedZein/ITI_XML/Day two/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "Untitled2.dtd">
<?xml-stylesheet type="text/css" href="employee.css"?>
<company>

<employee id="_1">
<name>Omar</name>
<email>omar@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">0353338888</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>Abouqer</street>
<buildingnumber>25</buildingnumber>
<region>Elraml</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>


<employee id="_2">
<name>Ahmed</name>
<email>ahmed@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>smouha</street>
<buildingnumber>25</buildingnumber>
<region>Elraml</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>

<employee id="_3">
<name>Ali</name>
<email>ALI@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>ELmamora</street>
<buildingnumber>25</buildingnumber>
<region>Elmontaza</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>

<employee id="_3">
<name>emad</name>
<email>emmmmaaad@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>ELmamora</street>
<buildingnumber>25</buildingnumber>
<region>Elmontaza</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>
<employee id="_3">
<name>hassan</name>
<email>hassan@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>ELmamora</street>
<buildingnumber>25</buildingnumber>
<region>Elmontaza</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>


<employee><name>Ali</name><email>ALI@test.com</email><phones><phone type="mobile">035344</phone></phones><addresses><street>ELmamora</street></addresses></employee><employee><name>emad</name><email>emmmmaaad@test.com</email><phones><phone type="mobile">0106666666</phone></phones><addresses><street>ELmamora</street></addresses></employee><employee><name>Ahmed</name><email>ahmed@test.com</email><phones><phone type="mobile">0353338888</phone></phones><addresses><street>smouha</street></addresses></employee><employee><name>emad</name><email>emmmmaaad@test.com</email><phones><phone type="mobile">0106666666</phone></phones><addresses><street>ELmamora</street></addresses></employee><employee><name>omar alaa mansor</name><email>oioioioid@test.com</email><phones><phone type="mobile">01063337988</phone></phones><addresses><street>sedibeshr, 23,9,algehhadburj,30st</street></addresses></employee><employee><name>hassan</name><email>hassan@test.com</email><phones><phone type="mobile">035333</phone></phones><addresses><street>ELmamora</street></addresses></employee><employee><name>Ali</name><email>ALI@test.com</email><phones><phone type="mobile">035344</phone></phones><addresses><street>ELmamora</street></addresses></employee></company>
<!-- <employee id="_3">
<name>emad</name>
<email>emad@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>ELmamora</street>
<buildingnumber>25</buildingnumber>
<region>Elmontaza</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee>
<employee id="_3">
<name>hassan</name>
<email>hassan@test.com</email>
<phones>
<phone type="mobile">0106666666</phone>
<phone type="home">035333</phone> 
<phone type="work">035344</phone>
</phones>
<addresses>
<address>
<street>ELmamora</street>
<buildingnumber>25</buildingnumber>
<region>Elmontaza</region>
<city>Alexandria</city>
<country>Egypt</country>
</address>
</addresses>
</employee> -->
